# Generated by Django 4.1 on 2022-08-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('material_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Caps')),
            ],
            options={
                'verbose_name_plural': '4. Caps',
            },
        ),
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.PositiveIntegerField(unique=True)),
                ('address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': '5. Cotact forms',
            },
        ),
        migrations.CreateModel(
            name='safetyWears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('material_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='safetyWears')),
            ],
            options={
                'verbose_name_plural': '1. Safety Wears',
            },
        ),
        migrations.CreateModel(
            name='tshirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('material_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='T-shirts')),
            ],
            options={
                'verbose_name_plural': '2. T-shirts',
            },
        ),
        migrations.CreateModel(
            name='uniforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('material_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Uniforms')),
            ],
            options={
                'verbose_name_plural': '3. Uniforms',
            },
        ),
    ]
