# Generated by Django 4.1 on 2022-08-31 14:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caps',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Caps'),
        ),
        migrations.AlterField(
            model_name='safetywears',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='safetyWears'),
        ),
        migrations.AlterField(
            model_name='tshirts',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='T-shirts'),
        ),
        migrations.AlterField(
            model_name='uniforms',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Uniforms'),
        ),
    ]
